# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e35d84a42fb221799b65a55288898db8392da8d4258c1d7cefe735864bcc871a7d120805c27bf18223b241f754d0ac3001e2528a6bca5e19e3943c39ef596681

test:
  secret_key_base: ee83c53e50a1c2f1a14bf25d122eb56c438e4a1bb7ad54bb4d2339eaca1d9f110cec46b19faba1dbccc7d09cd1ee830f2835e0ce9ad7e0cdee300b2616e037b8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
